config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'
  get '/pages', to: 'pages#index'
  
  get '/registration', to: 'users#new'
  post '/registration', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  get '/reset_password', to: 'reset_password#new'
  post '/reset_password', to: 'reset_password#create'
  get '/reset_password/edit', to: 'reset_password#edit'
  patch '/reset_password/update', to: 'reset_password#update'

  
  # get '/poll/invite/:id/find', to: 'polls#invite', as: 'find'
  # post '/poll/invite/:id', to: 'polls#invite_user', as: 'invite'

  resources :polls do 
    resources :invites, only: [:new, :create]
    resources :votes, only: [:update]
  end

 

end

app/controllers/reset_password_controller.rb
# frozen_string_literal: true

class ResetPasswordController < ApplicationController
  def new
    authorize! User, to: :reset_password?
  end

  def create
    authorize! User, to: :reset_password?
    @user = User.find_by(email: params[:email])

    ResetPasswordMailer.reset(@user).deliver_later if @user
    redirect_to root_path, success: I18n.t('flash.success.reset_password')
  end

  def edit
    authorize! User, to: :reset_password?
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to login_path, error: I18n.t('flash.error.token_expire')
  end

  def update
    authorize! User, to: :reset_password?
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
    @user.update(password_params)
    if @user.save
      redirect_to login_path, success: I18n.t('flash.success.update')
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/reset_password/_password_reset_form.html.erb
<%= form_with model: @user, url: reset_password_update_path(token: params[:token]), class: "border rounded p-4 mt-5" do |form|%>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <% form.object.errors.full_messages.each do |msg|%>
        <div><%= msg %></div>
      <%end%>
    </div>
  <% end %>
  <h5>Set new password</h5>
  <div class="mb-3">
  <%= form.password_field :password, class: "form-control", placeholder: "Password"%>
  </div> 
  <div class="mb-3">
  <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirmation"%>
  </div>
  <div class="mb-3 d-flex justify-content-between pe-5">
    <%= form.submit "Change password", class: "btn btn-primary" %>
  </div> 
<% end %>

app/views/reset_password/_reset_form.html.erb
<%= form_tag reset_password_path, method: :post, class: "border rounded p-4 mt-5" do%>
  <h5>Resset your password</h5>
  <div class="mb-3">
    <%= email_field_tag :email, params[:email], class: "form-control", placeholder: "Email" %>
  </div> 
  <div class="mb-3 d-flex justify-content-between pe-5">
    <%= submit_tag "Reset password", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reset_password/edit.html.erb
<div class="container-sm">
  <div class="row justify-content-center">
    <div class="col-4 align-self-center">
      <% if allowed_to?(:reset_password?, User)%>
        <%= render "password_reset_form"%>
      <% end %>  
    </div>
  </div>
</div>

app/views/reset_password/new.html.erb
<div class="container-sm">
  <div class="row justify-content-center">
    <div class="col-4 align-self-center">
      <% if allowed_to?(:reset_password?, User)%>
        <%= render "reset_form"%>
      <% end %>  
    </div>
  </div>
</div>