config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'
  get '/pages', to: 'pages#index'
  
  get '/registration', to: 'users#new'
  post '/registration', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  get '/reset_password', to: 'reset_password#new'
  post '/reset_password', to: 'reset_password#create'
  get '/reset_password/edit', to: 'reset_password#edit'
  patch '/reset_password/update', to: 'reset_password#update'

  
  # get '/poll/invite/:id/find', to: 'polls#invite', as: 'find'
  # post '/poll/invite/:id', to: 'polls#invite_user', as: 'invite'

  resources :polls do 
    resources :invites, only: [:new, :create]
    resources :votes, only: [:update]
  end

 

end

app/views/password_reset/_password_reset_form.html.erb
<%= form_with model: @user, url: password_reset_update_path(token: params[:token]), class: "border rounded p-4 mt-5" do |form|%>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <% form.object.errors.full_messages.each do |msg|%>
        <div><%= msg %></div>
      <%end%>
    </div>
  <% end %>
  <h5>Set new password</h5>
  <div class="mb-3">
  <%= form.password_field :password, class: "form-control", placeholder: "Password"%>
  </div> 
  <div class="mb-3">
  <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirmation"%>
  </div>
  <div class="mb-3 d-flex justify-content-between pe-5">
    <%= form.submit "Change password", class: "btn btn-primary" %>
  </div> 
<% end %>

app/views/password_reset/_reset_form.html.erb
<%= form_tag password_reset_path, method: :post, class: "border rounded p-4 mt-5" do%>
  <h5>Resset your password</h5>
  <div class="mb-3">
    <%= email_field_tag :email, params[:email], class: "form-control", placeholder: "Email" %>
  </div> 
  <div class="mb-3 d-flex justify-content-between pe-5">
    <%= submit_tag "Reset password", class: "btn btn-primary" %>
  </div>
<% end %>