config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'
  get '/pages', to: 'pages#index'
  
  get '/registration', to: 'users#new'
  post '/registration', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  get '/reset_password', to: 'reset_password#new'
  post '/reset_password', to: 'reset_password#create'
  get '/reset_password/edit', to: 'reset_password#edit'
  patch '/reset_password/update', to: 'reset_password#update'

  
  # get '/poll/invite/:id/find', to: 'polls#invite', as: 'find'
  # post '/poll/invite/:id', to: 'polls#invite_user', as: 'invite'

  resources :polls do 
    resources :invites, only: [:new, :create]
    resources :votes, only: [:update]
  end

 

end

app/views/shared/_form.html.erb
<%= form_tag "/pages/registration", method: :post, class: "border rounded p-4 mt-5" %>
  <div class="mb-3">
    <%= text_field_tag :username, params[:username], placeholder: "Username", class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= email_field_tag  :email, params[:email], placeholder: "Email", class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= password_field_tag 'password', nil, class: "form-control", placeholder: "Password" %>
  </div>
  <div class="mb-3">
    <%= password_field_tag  'password_confirmation', nil, class: "form-control", placeholder: "Confirmation" %>
  </div>
  <div class="mb-3 d-flex justify-content-between pe-5"> 
    <%= submit_tag "Register", method: :post, class: "btn btn-primary" %>
    <div class="form-check">
      <%= check_box_tag :remember_me, :yes, false, class: "form-check-input" %>
      <%= label_tag :remember_me, "Remember me", class: "form-check-label" %>
    </div>
  </div>   

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <%= link_to "Fun Poll", root_path, class: "navbar-brand"%>
          <ul class="navbar-nav">
            <% if current_user%>
              <li class="nav-item">
                <p class="nav-link text-primary"><%= current_user.username %></p>
              </li>
              <li class="nav-item">
                  <%= link_to "My Poll", polls_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <% if allowed_to?(:destroy?, :session)%>
                  <%= link_to "Logout", logout_path, method: :delete, class: 'nav-link text-dark' %>
                <% end %>
              </li>
            <% else %>  
              <li class="nav-item">
                <% if allowed_to?(:create?, User)%>
                  <%= link_to "Register", registration_path, class: "nav-link text-dark"%>
                <% end %>
              </li>
              <li class="nav-item">
                <% if allowed_to?(:create?, :session)%>
                  <%= link_to "Login", login_path, class: 'nav-link text-dark'%>
                <% end %>
              </li>
            <% end %>  
          </ul>
        </div>
      </nav>

app/views/shared/_registr_form.html.erb
<%= form_with model: @user, url: registration_path, method: :post, class: "border rounded p-4 mt-5" do |form|%>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <% @user.errors.full_messages.each do |msg|%>
        <div><%= msg %></div>
      <%end%>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.text_field :username, placeholder: "Username", class: "form-control" %>
  </div> 
  <div class="mb-3">
    <%= form.email_field :email, placeholder: "Email", class: "form-control" %>
  </div> 
  <div class="mb-3">
    <%= form.password_field :password, placeholder: "Password", class: "form-control"%>
  </div> 
  <div class="mb-3">
    <%= form.password_field :password_confirmation, placeholder: "Confirmation", class: "form-control"%>  
  </div> 
  <div class="mb-3">
    <%= form.submit method: :post, class: "btn btn-primary" %>  
  </div>
<% end %>    