config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'
  get '/pages', to: 'pages#index'
  
  get '/registration', to: 'users#new'
  post '/registration', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  get '/reset_password', to: 'reset_password#new'
  post '/reset_password', to: 'reset_password#create'
  get '/reset_password/edit', to: 'reset_password#edit'
  patch '/reset_password/update', to: 'reset_password#update'

  
  # get '/poll/invite/:id/find', to: 'polls#invite', as: 'find'
  # post '/poll/invite/:id', to: 'polls#invite_user', as: 'invite'

  resources :polls do 
    resources :invites, only: [:new, :create]
    resources :votes, only: [:update]
  end

 

end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :user
  has_many :memberships, class_name: 'PollMembership', foreign_key: "poll_id"
  has_many :members, -> { distinct }, through: :memberships, source: :user, dependent: :destroy
  has_many :options, class_name: "PollOption", dependent: :destroy

  accepts_nested_attributes_for :options, allow_destroy: true, reject_if: lambda {|attributes| attributes['vote_option'].blank?}
  

  validates :title, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_before_start_date

  scope :upcoming, -> { where('start_date > ?', Date.today) }
  scope :active, -> { where('start_date <= ? and end_date >= ?', Date.today, Date.today) }
  scope :ended, -> { where('end_date < ?', Date.today) }

  private  
  def end_date_before_start_date
    return if start_date.blank? || end_date.blank?

    errors.add(:end_date, "can't be earlier than start date ") if end_date <= start_date
  end
  


end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  rescue_from ActiveRecord::RecordNotFound do 
    redirect_to polls_path, error: I18n.t('flash.poll.not_found')
  end

  def index
    authorize! Poll, to: :index?  
    @active = current_user.polls.active
    @upcoming = current_user.polls.upcoming
    @ended = current_user.polls.ended
  end

  def show
    @poll = Poll.find(params[:id])
    authorize! @poll, to: :show?
    @options = @poll.options
    @members = @poll.members.count
  end

  def new
    authorize! Poll, to: :create?
    @poll = Poll.new
    2.times { @poll.options.build }
  end

  def create
    authorize! Poll, to: :create?
    @poll = current_user.own_polls.new(poll_params)
    if @poll.save 
      @poll.members << current_user
      redirect_to polls_path, success: I18n.t('flash.poll.create')
    else
      render :new
    end
  end

  def edit
    @poll = Poll.find(params[:id])
    @options = @poll.options
    authorize! @poll, to: :update?
  end

  def update
    @poll = Poll.find(params[:id])
    authorize! @poll, to: :update?
    
    if @poll.update(poll_params)
      redirect_to poll_path(@poll.id), success: I18n.t('flash.poll.update')
    else
      render :new
    end
  end

  def destroy
    @poll = Poll.find(params[:id])
    authorize! @poll, to: :destroy?
    @poll.destroy
    redirect_to polls_path, success: I18n.t('flash.poll.deleted')
  end


  private

  def poll_params
    params.require(:poll).permit(:title, :description, :start_date, :end_date, options_attributes: [:id, :vote_option, :_destroy])
  end
end

app/views/polls/_active.html.erb
<div class="card mb-3 shadow-sm p-3 mb-5 bg-body rounded">
      <div class="card-body">
        <div class="row">
          <div class="col-8">
            <h6>Title</h6>
            <%= link_to active.title, active, class: "nav-link" %>
          </div>
          <div class="col-2">
            <h6>Author</h6>
            <p class="text-info"><%= active.user.username %></p>
          </div>
          <div class="col-2">
            <h6>Start date</h6>
            <p><%= active.start_date %></p>
          </div>
        </div>
      </div>
</div>

app/views/polls/_edit_poll_form.html.erb
<%= form_for @poll, method: :patch, class: "border rounded p-4 mt-5" do |f| %>   
    <% if f.object.errors.any? %>  
      <div class="alert alert-danger">
          <%= f.object.errors.full_messages.each do |msg| %>
            <div><%= msg %></div>
          <% end %>
      </div>
      <% end %>  
    
    <div class="mb-3">
      <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
    </div> 
    <div class="mb-3">
      <%= f.text_area :description, placeholder: "Description", class: "form-control" %>
    </div>
    <div class="row"> 
      <div class="col-6 mb-3 d-flex flex-column">
        <%= f.label :start_date, class: "form-label"%>
        <%= f.date_field :start_date, class: "form-control"%>
      </div> 
      <div class="col-6 mb-3 d-flex flex-column">
        <%= f.label :end_date, class: "form-label"%>
        <%= f.date_field :end_date, class: "form-control"%>  
      </div>
    </div>
    <div class="row" id="options">
        <%= f.fields_for :options, method: :patch do |option| %>
          <div class="col-4"> 
            <%= option.text_field :vote_option, placeholder: 'Option', class: "form-control" %>
            <%= option.check_box :_destroy %>
          </div>
        <% end %>
    </div> 
    <div class="row d-flex justify-content-between">      
      <div class="col-3">
        <%= f.submit "Edit poll", class: "btn btn-primary" %>   
      </div>
      <div class="col-5">
        <%= f.button "Add option", class: "btn btn-success", style: "width: 100%;" %>  
      </div>
    </div>
  <% end %>

app/views/polls/_ended.html.erb
<div class="card mb-3 shadow-sm p-3 mb-5 bg-body rounded">
      <div class="card-body">
        <div class="row">
          <div class="col-8">
            <h6>Title</h6>
            <%= link_to ended.title, ended, class: "nav-link" %>
          </div>
          <div class="col-2">
            <h6>Author</h6>
            <p class="text-info"><%= ended.user.username %></p>
          </div>
          <div class="col-2">
            <h6>End date</h6>
            <p><%= ended.start_date %></p>
          </div>
        </div>
      </div>
</div>

app/views/polls/_invite_form.html.erb
<%= form_tag invite_path, method: :post, class: "border rounded p-4 mt-5" do %> 
  <div class="mb-3">
      <%= text_field_tag :username, params[:username], class: "form-control" %>
  </div> 
  <div class="col-3">
      <%= submit_tag "Send invite", class: "btn btn-primary" %>     
  </div>
<% end %>

app/views/polls/_new_poll_form.html.erb
  <%= form_for @poll, class: "border rounded p-4 mt-5" do |f| %>   
    <% if f.object.errors.any? %>  
      <div class="alert alert-danger">
          <%= f.object.errors.full_messages.each do |msg| %>
            <div><%= msg %></div>
          <% end %>
      </div>
      <% end %>  
    
    <div class="mb-3">
      <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
    </div> 
    <div class="mb-3">
      <%= f.text_area :description, placeholder: "Description", class: "form-control" %>
    </div>
    <div class="row"> 
      <div class="col-6 mb-3 d-flex flex-column">
        <%= f.label :start_date, class: "form-label"%>
        <%= f.date_field :start_date, class: "form-control"%>
      </div> 
      <div class="col-6 mb-3 d-flex flex-column">
        <%= f.label :end_date, class: "form-label"%>
        <%= f.date_field :end_date, class: "form-control"%>  
      </div>
    </div>
    <div class="row" id="options">
        <%= f.fields_for :options do |option| %>
          <div class="col-4">
            <%= option.text_field :vote_option, placeholder: 'Option', class: "form-control" %>
            <%= option.check_box :_destroy %>
          </div>
        <% end %>
    </div> 
    <div class="row d-flex justify-content-between">      
      <div class="col-3 pt-3">
        <%= f.submit "Add poll", class: "btn btn-primary" %>     
      </div>
      <div class="col-5 pt-3">
        <button class="btn btn-success" id="btn">Add option</button>
      </div>
    </div>
  <% end %>

app/views/polls/_options.html.erb
<div class="row">
  <div class="col-6 ">
  <%= form_for options, url: poll_vote_path(@poll.id), method: :patch do |f|%>
    <%= f.submit options.vote_option, class: 'nav-link border mb-1'%>
  <% end %>  
  </div>
</div>

app/views/polls/_result.html.erb
<div class="row">
  <div class="col-6 ">
    <div class='nav-link border w-75'><%= options.vote_option %></div>  
  </div>
</div>

app/views/polls/_upcoming.html.erb
<div class="card mb-3 shadow-sm p-3 mb-5 bg-body rounded">
      <div class="card-body">
        <div class="row">
          <div class="col-8">
            <h6>Title</h6>
            <%= link_to upcoming.title, upcoming, class: "nav-link" %>
          </div>
          <div class="col-2">
            <h6>Author</h6>
            <p class="text-info"><%= upcoming.user.username %></p>
          </div>
          <div class="col-2">
            <h6>Start date</h6>
            <p><%= upcoming.start_date %></p>
          </div>
        </div>
      </div>
</div>

app/views/polls/edit.html.erb
<div class="container-sm">
  <div class="row justify-content-center">
    <div class="col-4 align-self-center">
      <h1>Edit your poll.</h1>
        <%= render "edit_poll_form" %>
    </div>
  </div>
</div>

app/views/polls/index.html.erb
<div class="container-fluid" style="padding-top: 45px;">
  <div class="d-flex flex-row justify-content-between align-items-center">
    <h1>Your poll</h1>
    <%= link_to '+ New Poll', new_poll_path, class: "btn btn-primary"%>
  </div>
  <div class="container">
    <div class="row justify-content-between pb-3">
      <% if current_user.polls.empty?%>
        <h3>You have no polls yet.</h3>
      <% else %>  
        <h3>Uppcoming polls</h3>
          <%= render partial: "upcoming", collection: @upcoming %>
        <h3>Active polls</h3>
          <%= render partial: "active", collection: @active %>
        <h3>Closed pools</h3>
          <%= render partial: "ended", collection: @ended%>
      <% end %>    
    </div>
  </div>  
</div>

app/views/polls/invite.html.erb
<div class="container-sm">
  <div class="row justify-content-center">
    <div class="col-4 align-self-center">
      <h1>Invite friends to poll.</h1>
        <p>Type username or email</p>
        <%= render "invite_form"%>
    </div>
  </div>
</div>

app/views/polls/invite_user.html.erb
<div class="container-sm">
  <div class="row justify-content-center">
    <div class="col-4 align-self-center">
      <h1>Invite friends to poll.</h1>
        <p>Type username or email</p>
        <%= render "invite_form"%>
    </div>
  </div>
</div>

app/views/polls/new.html.erb
<div class="container-sm">
  <div class="row justify-content-center">
    <div class="col-4 align-self-center">
      <h1>Create your own poll.</h1>
        <%= render "new_poll_form"%>
    </div>
  </div>
</div>

app/views/polls/show.html.erb
<div class="container-fluid" style="padding-top: 35px; padding-bottom: 50px;" id="poll" data-poll-id=<%= @poll.id%>>
  <div class="row">
    <div class="col-7">
      <h3><%= @poll.title %></h3>
    </div>
    <div class="col-5 d-flex justify-content-between ">
      <% if allowed_to?(:invite?, @poll ) %>
        <%= link_to "Invite user", new_poll_invite_path(@poll.id), class:"btn btn-success pl-1 pr-1 w-50"%>
      <% end %>
      <% if allowed_to?(:update?, @poll ) %>  
        <%= link_to "Edit poll", edit_poll_path(@poll.id), class:"btn btn-warning pl-1 pr-1 w-50"%>
      <% end %>  
      <% if allowed_to?(:destroy?, @poll ) %>
        <%= link_to "Delete poll", @poll, method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger pl-1 pr-1 w-50"%>
      <% end %>
    </div>
  </div>
  <div class="row gx-5">
    <div class="col-7">
      <div class="card mt-3 shadow-sm p-3 mb-5 bg-body rounded">
        <div class="card-body">
          <h5>Details</h5>
          <p class="fs-6">Description</p>
          <p><%= @poll.description %></p>
          <div class="row justify-content-between">
            <div class="col-3">
              <p>Start date</p>
              <p><%= @poll.start_date %></p>
            </div>
            <div class="col-3">
              <p>End date</p>
              <p><%= @poll.end_date %></p>
            </div>
          </div>
          <p class="fs-6">Participians count <%= @members%></p>
        </div>
      </div>
    </div>
    <div class="col-5">
      <div class="card mt-3 shadow-sm p-3 mb-5 bg-body rounded">
        <div class="card-body"> 
          <%= render partial: 'options', collection: @options%>
        </div>
      </div>
    </div>   
  </div>  
  <div class="row justify-content-center ">
    <div class=" col-10 overflow-auto align-self-center border-top border-2 p-5 " id="chat_holder" style="height: 350px">
    </div>
    <form class="input-group w-75 p-2">
      <input type="text" class="form-control" id="message_input" placeholder="Type message" aria-label="Recipient's username" aria-describedby="button-addon2">
      <button class="btn btn-outline-secondary" type="button" id="button-addon2">Button</button>
    </form>
  </div>
</div>